CREATE TABLE NCOWN.DBDEV_LOG
(
  DBDEV_LOG_ID           NUMBER,
  TAG                    VARCHAR2(100 BYTE),
  CTIME                  DATE,
  MTIME                  DATE,
  TIMER                  NUMBER,
  MODULE                 VARCHAR2(100 BYTE),
  ACTION                 VARCHAR2(100 BYTE),
  NOTES                  CLOB,
  SIGNON_ID              NUMBER,
  SESSID                 NUMBER,
  ERRNBR                 NUMBER,
  ERRMSG                 VARCHAR2(2000 BYTE),
  CURRENT_USER           VARCHAR2(100 BYTE),
  TERMINAL               VARCHAR2(100 BYTE),
  IP_ADDRESS             VARCHAR2(100 BYTE),
  OS_USER                VARCHAR2(100 BYTE),
  CURRENT_SCHEMA         VARCHAR2(100 BYTE),
  SERVER_HOST            VARCHAR2(100 BYTE),
  SERVICE_NAME           VARCHAR2(100 BYTE),
  SESSION_USER           VARCHAR2(100 BYTE),
  INSTANCE_NAME          VARCHAR2(100 BYTE),
  V$SESSION_MODULE       VARCHAR2(64 BYTE),
  V$SESSION_ACTION       VARCHAR2(64 BYTE),
  V$SESSION_CLIENT_INFO  VARCHAR2(64 BYTE)
)
LOB (NOTES) STORE AS BASICFILE (
  TABLESPACE  TS_T3OWN_DATA
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                 ))
TABLESPACE USERS
/


CREATE INDEX NCOWN.X1_DBDEV_LOG ON NCOWN.DBDEV_LOG
(TAG, DBDEV_LOG_ID)
TABLESPACE USERS
/

CREATE OR REPLACE TRIGGER NCOWN.BIUR_DBDEV_LOG
  BEFORE INSERT OR UPDATE ON NCOWN.DBDEV_LOG
  FOR EACH ROW
BEGIN
  IF :NEW.dbdev_log_id IS NULL THEN
    :NEW.dbdev_log_id := dbdev_log_seq.NEXTVAL;
    :NEW.ctime        := SYSDATE;
  END IF;
  
  :NEW.mtime := SYSDATE;
  
END buir_debdev_log;
/


CREATE OR REPLACE PUBLIC SYNONYM DBDEV_LOG FOR NCOWN.DBDEV_LOG
/


GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO AMOHAMMED
/

GRANT SELECT ON NCOWN.DBDEV_LOG TO APP_SUPPORT_ROLE
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO AROSENTHAL
/

GRANT SELECT ON NCOWN.DBDEV_LOG TO BI_STAGE
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO BVADUKOOT
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO CSPENCE
/

GRANT SELECT ON NCOWN.DBDEV_LOG TO DB_APP_SUPPORT
/

GRANT DELETE, INSERT, UPDATE ON NCOWN.DBDEV_LOG TO DEV_DBDEVELOPER_ROLE
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO ICHANDRABHATTA
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO KKONDA
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO KVOEGELE
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO LFLOYD
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO MYADAGERI
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO NC
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO NCEDA2
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO NCEDA3
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO NCEDA4
/

GRANT SELECT ON NCOWN.DBDEV_LOG TO NCOWN_READ
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO NC_APP
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO PCHAKRABORTY
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO PMEDI
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO PSING
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO PUBLIC
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO RMUDLIAR
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO SBHEEMIREDDY
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO SCHANDRATRE
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO SKOLLI
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO SSASSON
/

GRANT DELETE, INSERT, SELECT, UPDATE ON NCOWN.DBDEV_LOG TO VKARIYALA
/
